// Code generated by Kitex v0.6.2. DO NOT EDIT.

package messageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	message "simple-douyin/kitex_gen/message"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	MessageChat(ctx context.Context, request *message.MessageChatRequest, callOptions ...callopt.Option) (r *message.MessageChatResponse, err error)
	MessageSend(ctx context.Context, request *message.MessageSendRequest, callOptions ...callopt.Option) (r *message.MessageSendResponse, err error)
	MessageGetUserLastMessage(ctx context.Context, request *message.MessageGetUserLastMessageRequest, callOptions ...callopt.Option) (r *message.MessageGetUserLastMessageResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) MessageChat(ctx context.Context, request *message.MessageChatRequest, callOptions ...callopt.Option) (r *message.MessageChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MessageChat(ctx, request)
}

func (p *kMessageServiceClient) MessageSend(ctx context.Context, request *message.MessageSendRequest, callOptions ...callopt.Option) (r *message.MessageSendResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MessageSend(ctx, request)
}

func (p *kMessageServiceClient) MessageGetUserLastMessage(ctx context.Context, request *message.MessageGetUserLastMessageRequest, callOptions ...callopt.Option) (r *message.MessageGetUserLastMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MessageGetUserLastMessage(ctx, request)
}
