// Code generated by hertz generator.

package relation

import (
	mw "simple-douyin/api/biz/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	return nil
}

func _relationfollowlistMw() []app.HandlerFunc {
	// your code...
	// return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationfollowerlistMw() []app.HandlerFunc {
	// 该接口需要登录态
	// return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
	return nil
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationfriendlistMw() []app.HandlerFunc {
	// 该接口需要登录态
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _relationactionMw() []app.HandlerFunc {
	// 该接口需要登录态
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {

	// your code...
	//fmt.Println("in _list0Mw")
	return nil
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}
