// Code generated by hertz generator.

package message

import (
	mw "simple-douyin/api/biz/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _message_ctionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messagechatMw() []app.HandlerFunc {
	// 该接口需要登录态
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _messageactionMw() []app.HandlerFunc {
	// 该接口需要登录态
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}
